### ISSUE TITLE
ValueError: Unknown kernel transform "rp"

### ISSUE THREAD

**Issue by yux326** [Luoyadan/KECOR-active-3Ddet#2]
Hello, thanks for your work!
An error occoured when I run KECOR for PVRCNN Training:
ValueError: Unknown kernel transform "rp"

I noticed another issue about the same problem, how can I fix it?

Thanks again!

**Comment by Luoyadan** [comment]
Hi,

I will get it fixed tomorrow, sorry for the delay.

Cheers,
Yadan

Yadan Luo

School of Information Technology and Electrical Engineering

University of Queensland

Brisbane, Australia

**Comment by Luoyadan** [comment]
Hi yux326,

I have updated the NTK lib and it should work now.
Please let me know if there are any questions and happy to help.

Cheers,
Yadan

**Comment by yux326** [comment]
Hello, I have used the nwew code and it works, thank you so much!
However, I meet another bug with Second model, I have add a new issue(#3 ).
Hope you could help fix it.

Thanks again for your help!

Yux
