### ISSUE TITLE
KeyError: 'rcnn_cls_gt'

### ISSUE THREAD

**Issue by yux326** [Luoyadan/KECOR-active-3Ddet#3]
Hello, thanks for the work!
An error occured when training Second model with KECOR:

```Traceback (most recent call last):
  File "train.py", line 313, in <module>
    main()
  File "train.py", line 255, in main
    dist_train=dist_train
  File "/home/KECOR-active-3Ddet/tools/train_utils/train_active_utils.py", line 313, in train_model_active
    accumulated_iter=accumulated_iter
  File "../pcdet/utils/active_training_utils.py", line 271, in select_active_labels
    selected_frames = strategy.query(leave_pbar, cur_epoch)
  File "../pcdet/query_strategies/kecor_sampling.py", line 52, in query
    cls_train.append(train_pred_dicts['rcnn_cls_gt'])
KeyError: 'rcnn_cls_gt'
```
This happens after the pre-train is finished.
Could you please help fix that? Thanks again.

**Comment by RuiyuM** [comment]
I meet the same error how did you fix the KeyError: 'rcnn_cls_gt' bug?

**Comment by Luoyadan** [comment]
![image](https://github.com/Luoyadan/KECOR-active-3Ddet/assets/17021756/eeb718ab-5d7e-4332-92e3-c6169c9f96c6)
Hi all,

Sorry for the belated reply. I think I may accidentally overwrite the second_net_iou.py. So just copy these lines under ret_dict should resolve the issue. I will also provide all data for plotting the AL results.

Cheers,
Yadan

**Comment by yux326** [comment]
Thanks for your help.
I have fixed it and it runs with no bug.
